package versions

import (
	"context"
	"fmt"

	dbinternal "github.com/xxnuo/open-coreui/backend/open_webui/internal"
)

const (
	CA81BD47C050Revision     = "ca81bd47c050"
	CA81BD47C050DownRevision = "7e5b5dc7342b"
)

func UpgradeCA81BD47C050AddConfigTable(ctx context.Context, db *dbinternal.Handle) error {
	exists, err := db.TableExists(ctx, "config")
	if err != nil {
		return err
	}
	if exists {
		return nil
	}

	switch db.Dialect {
	case dbinternal.DialectSQLite:
		_, err = db.DB.ExecContext(ctx, `
			CREATE TABLE config (
				id INTEGER PRIMARY KEY AUTOINCREMENT,
				data JSON NOT NULL,
				version INTEGER NOT NULL DEFAULT 0,
				created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
				updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
			)
		`)
		return err
	case dbinternal.DialectPostgres:
		tableName := "config"
		if db.Schema != "" {
			tableName = db.Schema + ".config"
		}
		_, err = db.DB.ExecContext(ctx, `
			CREATE TABLE `+tableName+` (
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				data JSON NOT NULL,
				version INTEGER NOT NULL DEFAULT 0,
				created_at TIMESTAMP NOT NULL DEFAULT NOW(),
				updated_at TIMESTAMP DEFAULT NOW()
			)
		`)
		return err
	default:
		return fmt.Errorf("unsupported dialect: %s", db.Dialect)
	}
}
